name: 03-runner workflow

on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: show os
              run: |
                echo "This job is running in ubuntu latest"
                echo "Runner OS $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: show os
              shell: bash
              run: |
                echo "This job is running in windows latest"
                echo "Runner OS $RUNNER_OS"
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: show os
              run: |
                echo "This job is running in windows latest"
                echo "Runner OS $RUNNER_OS"