name: 03-runner workflow

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: show os
              run: |
                echo "This job is running in ubuntu latest"
                echo "Runner OS $RUNNER_OS"