name: checkout github repo
on: [push]

jobs:
    check-out-action:
        runs-on: ubuntu-latest
        steps:
            - name: list files before
              run: ls -a
            - uses: actions/checkout@v4
            - name: list files after
              run: ls -a

    checkout-get-repo:
        runs-on: ubuntu-latest
        steps:
            - name: list files before
              run: ls -a
            - name: checkout 
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files after
              run: ls -a
