name: expression and contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: 'Expression & Contexts by @${{github.actor}}, event: ${{github.event}}'
jobs:
    using-exp-and-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: expression
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'this is a string'}}
                echo ${{ null}}
                echo ${{true}}
                echo ${{1>2}}
                echo ${{'string' == 'String'}}
                echo ${{ true && false}}
                echo ${{ true || (true && false) }}
            - name: dump contexts
              run: |
                echo '${{ toJson(github)}}'
                echo '${{ toJson(job)}}'
                echo '${{ toJson(secrets)}}'
                echo '${{ toJson(steps)}}'
                echo '${{ toJson(runner)}}'
