name: First Workflow
on: workflow_dispatch

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello World"
      - name: Multi line commands
        run: |
          node -v
          npm -v

  parallel-job:
    runs-on: macos-latest
    steps:
      - name: view sw version
        run: sw_vers

  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output " Windows String"