name: Selective Job Runner
on:
  push:
    branches: [main]

jobs:
  call-template:
    uses: ./.github/workflows/template_1.yml
    with:
      run-build: true
      run-test: true
      run-deploy: false  # Skip deploy