name: Selective Job Runner
on:
  push:
    branches: [main]
  
  workflow_dispatch:
    inputs:
      branchDeploy:
        description: 'Test'
        type: boolean
        default: false

jobs:
  call-template:
    uses: ./.github/workflows/teamplate_1.yaml
    if: inputs.branchDeploy == true
    with:
      run-build: true
      run-test: true
      run-deploy: false  # Skip deploy