name: env-approval-demo
on: [push, workflow_dispatch]

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "First job completed"

  approvalJob:
    needs: firstJob
    runs-on: ubuntu-latest
    environment: production
    continue-on-error: true
    steps:
      - run: echo "Approval step"

  approvedJob:
    needs: approvalJob
    if: ${{ needs.approvalJob.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approved path"

  rejectedJob:
    needs: approvalJob
    if: ${{ needs.approvalJob.result == 'failure' || needs.approvalJob.result == 'cancelled' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Rejected path"

  alwaysSucceed:
    needs: [approvedJob, rejectedJob]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: echo "Workflow completed as expected"