name: working dir
on: [push]
defaults:
    run:
        shell: bash
jobs:
    display:
        runs-on: ubuntu-latest
        steps:
            - name: Dispaly working dir
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: working dir
              working-directory: /home/runner
              run: |
                pwd
                ls -a

    display_windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Dispaly working dir
              run: |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
            - name: python-shell
              shell: python
              run: |
                import platform
                print(platform.processor())